name: 🚀 Epic
description: Define a new epic that groups multiple user stories.
assignees:
  - # Add default assignees if needed
body:
  - type: textarea
    id: business_goal
    attributes:
      label: Business Goal
      description: What business goal does this epic achieve?
    validations:
      required: true

  - type: textarea
    id: success_metrics
    attributes:
      label: Success Metrics
      description: How will you measure the success of this epic?
      placeholder: |
        - **Metric:** [e.g., Increase user engagement by 15%]
        - **Measurement:** [e.g., Tracked via analytics dashboard]
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope (Optional)
      description: What is explicitly not included in this epic?
    validations:
      required: false